import {
  p1,
  p10,
  p2,
  p3,
  p4,
  p5,
  p6,
  p7,
  p8,
  p9,
  post1,
  post10,
  post2,
  post3,
  post4,
  post5,
  post6,
  post7,
  post8,
  post9,
} from "./assets";



export const Users = [
  {
    id: 101,
    profilePicture: p1,
    username: "tech_guru",
  },
  {
    id: 102,
    profilePicture: p2,
    username: "nature_lover",
  },
  {
    id: 103,
    profilePicture: p3,
    username: "bookworm_98",
  },
  {
    id: 104,
    profilePicture: p4,
    username: "music_enthusiast",
  },
  {
    id: 105,
    profilePicture: p5,
    username: "chef_at_home",
  },
  {
    id: 106,
    profilePicture: p6,
    username: "fitness_freak",
  },
  {
    id: 107,
    profilePicture: p7,
    username: "traveler_88",
  },
  {
    id: 108,
    profilePicture: p8,
    username: "gamer_king",
  },
  {
    id: 109,
    profilePicture: p9,
    username: "fashionista_22",
  },
  {
    id: 110,
    profilePicture: p10,
    username: "artistic_vibes",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Exploring the mountains today! #Adventure",
    photo: post1,
    date: "10 minutes ago",
    userId: 101,
    like: 45,
    comment: 5,
  },
  {
    id: 2,
    desc: "A perfect day for a cozy book in the park. 📚🍃",
    photo: post2,
    date: "10 minutes ago",
    userId: 103,
    like: 32,
    comment: 9,
  },
  {
    id: 3,
    desc: "The best homemade pizza ever! 🍕 #CookingAtHome",
    photo: post3,
    date: "10 minutes ago",
    userId: 105,
    like: 50,
    comment: 10,
  },
  {
    id: 4,
    desc: "Just finished a 5-mile run, feeling great! #FitnessJourney",
    photo: post4,
    date: "10 minutes ago",
    userId: 106,
    like: 60,
    comment: 5,
  },
  {
    id: 5,
    desc: "Out in nature, soaking up the sun! 🌞",
    photo: post5,
    date: "10 minutes ago",
    userId: 102,
    like: 78,
    comment: 1,
  },
  {
    id: 6,
    desc: "Trying out this new game today! #GamerLife",
    photo: post6,
    date: "10 minutes ago",
    userId: 108,
    like: 120,
    comment: 3,
  },
  {
    id: 7,
    desc: "Fashion is all about comfort and confidence. #OOTD",
    photo: post7,
    date: "10 minutes ago",
    userId: 109,
    like: 90,
    comment: 9,
  },
  {
    id: 8,
    desc: "Another successful painting session. #ArtistLife 🎨",
    photo: post8,
    date: "10 minutes ago",
    userId: 110,
    like: 110,
    comment: 9,
  },
  {
    id: 9,
    desc: "Sunset views after a long day of traveling. #Wanderlust",
    photo: post9,
    date: "10 minutes ago",
    userId: 107,
    like: 135,
    comment: 19,
  },
  {
    id: 10,
    desc: "Listening to some music to unwind. 🎧 #RelaxingVibes",
    photo: post10,
    date: "10 minutes ago",
    userId: 104,
    like: 85,
    comment: 40,
  },
];
