export const questions = [
  {
    id: 1,
    question: "What is the capital of India?",
    options: ["Mumbai", "New Delhi", "Kolkata", "Chennai"],
    answer: "New Delhi",
  },
  {
    id: 2,
    question: "Which is the largest planet in our solar system?",
    options: ["Earth", "Mars", "Jupiter", "Venus"],
    answer: "Jupiter",
  },
  {
    id: 3,
    question: "Who wrote the national anthem of India?",
    options: [
      "Bankim Chandra Chatterjee",
      "Rabindranath Tagore",
      "Sarojini Naidu",
      "Subhash Chandra Bose",
    ],
    answer: "Rabindranath Tagore",
  },
  {
    id: 4,
    question: "Which festival is known as the 'Festival of Lights' in India?",
    options: ["Holi", "Diwali", "Eid", "Christmas"],
    answer: "Diwali",
  },
  {
    id: 5,
    question: "Which of these animals is known for its long neck?",
    options: ["Elephant", "Giraffe", "Lion", "Kangaroo"],
    answer: "Giraffe",
  },
  {
    id: 6,
    question: "Who was the first Prime Minister of independent India?",
    options: [
      "Mahatma Gandhi",
      "Jawaharlal Nehru",
      "Sardar Patel",
      "Lal Bahadur Shastri",
    ],
    answer: "Jawaharlal Nehru",
  },
  {
    id: 7,
    question: "Which of these is NOT a programming language?",
    options: ["Python", "JavaScript", "HTML", "Windows"],
    answer: "Windows",
  },
  {
    id: 8,
    question: "What is the chemical symbol for Gold?",
    options: ["Ag", "Au", "Pt", "Pb"],
    answer: "Au",
  },
  {
    id: 9,
    question: "Which Mughal emperor built the Taj Mahal?",
    options: ["Akbar", "Shah Jahan", "Aurangzeb", "Babur"],
    answer: "Shah Jahan",
  },
  {
    id: 10,
    question: "Who is known as the 'Missile Man of India'?",
    options: [
      "Vikram Sarabhai",
      "C.V. Raman",
      "A.P.J. Abdul Kalam",
      "Homi Bhabha",
    ],
    answer: "A.P.J. Abdul Kalam",
  },
  {
    id: 11,
    question: "Which Indian scientist won a Nobel Prize for Physics in 1930?",
    options: [
      "Homi Bhabha",
      "C.V. Raman",
      "Satyendra Nath Bose",
      "Venkatraman Ramakrishnan",
    ],
    answer: "C.V. Raman",
  },
  {
    id: 12,
    question: "In which year did India become a Republic?",
    options: ["1947", "1950", "1952", "1965"],
    answer: "1950",
  },
  {
    id: 13,
    question: "Which Indian state has the highest literacy rate?",
    options: ["Tamil Nadu", "Maharashtra", "Kerala", "Karnataka"],
    answer: "Kerala",
  },
  {
    id: 14,
    question: "Which of these elements has the highest melting point?",
    options: ["Tungsten", "Platinum", "Iron", "Carbon"],
    answer: "Tungsten",
  },
  {
    id: 15,
    question: "Who was the first Indian woman to go to space?",
    options: [
      "Sunita Williams",
      "Kalpana Chawla",
      "Rakesh Sharma",
      "Indira Gandhi",
    ],
    answer: "Kalpana Chawla",
  },
];
export const moneyPyramid = [
  { id: 1, amount: 1000 },
  { id: 2, amount: 2000 },
  { id: 3, amount: 3000 },
  { id: 4, amount: 5000 },
  { id: 5, amount: 10000 },
  { id: 6, amount: 20000 },
  { id: 7, amount: 40000 },
  { id: 8, amount: 80000 },
  { id: 9, amount: 160000 },
  { id: 10, amount: 320000 },
  { id: 11, amount: 640000 },
  { id: 12, amount: 1250000 },
  { id: 13, amount: 2500000 },
  { id: 14, amount: 5000000 },
  { id: 15, amount: 10000000 },
];
